'use client';
import React from 'react';
import seedrandom from 'seedrandom';
import { Highlighter } from 'shiki';

interface CodeDisplayProps {
  code: string;
  language: string;
  themeAccent: string;
  slug: string;
}

export const CodeDisplay: React.FC<CodeDisplayProps> = ({ code, language, themeAccent, slug }) => {
  const rng = seedrandom(slug);
  const commentStyle = rng() > 0.5 ? 'detailed' : 'minimal';

  const addComments = (code: string): string => {
    if (commentStyle === 'minimal') {
      // 极简风格：只添加简短的顶部注释
      return `#!/usr/bin/env python3
"""Generated by ScriptKill"""

${code}`;
    } else {
      // 详细风格：添加详细的 DevOps 原理说明
      if (language === 'python') {
        return `#!/usr/bin/env python3
"""
Generated by ScriptKill

DevOps Best Practices Applied:
1. Error Handling: Comprehensive try-except blocks to handle network failures
2. Logging: Structured logging for better observability
3. Environment Variables: Using python-dotenv for secure configuration
4. Retry Logic: Automatic retries for transient failures
5. Modularity: Clean, maintainable code structure

This script is production-ready and can be deployed in any environment.
"""

import logging
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

${code}`;
      } else if (language === 'yaml') {
        return `# Generated by ScriptKill
#
# DevOps Best Practices Applied:
# 1. Restart Policy: Always restart containers on failure
# 2. Healthchecks: Regular health checks to ensure service availability
# 3. Environment Variables: Secure configuration via .env file
# 4. Volumes: Persistent storage for data
# 5. Port Mapping: Proper port exposure for service access
#
# This docker-compose file is production-ready and follows industry best practices.

${code}`;
      } else {
        return `// Generated by ScriptKill
//
// DevOps Best Practices Applied:
// 1. Error Handling: Comprehensive error catching
// 2. Logging: Structured logging for better observability
// 3. Environment Variables: Secure configuration
// 4. Modularity: Clean, maintainable code structure
//
// This code is production-ready and follows industry best practices.

${code}`;
      }
    }
  };

  const codeWithComments = addComments(code);

  // 服务端渲染时使用 shiki 生成高亮 HTML
  const [highlightedCode, setHighlightedCode] = React.useState<string>('');
  const [error, setError] = React.useState<string>('');

  React.useEffect(() => {
    async function highlightCode() {
      try {
        const { createHighlighter } = await import('shiki');
        const highlighter = await createHighlighter({ themes: ['dracula'], langs: ['python', 'javascript', 'yaml'] });
        const highlighted = highlighter.codeToHtml(codeWithComments, { lang: language, theme: 'dracula' });
        setHighlightedCode(highlighted);
        setError('');
      } catch (err) {
        console.error('Error highlighting code:', err);
        setError('Failed to highlight code. Please try again later.');
      }
    }

    highlightCode();
  }, [codeWithComments, language]);

  return (
    <section className="mb-12">
      <h2 
        className="text-2xl font-bold text-slate-900 mb-4 pl-4"
        style={{ borderLeft: `4px solid ${themeAccent}` }}
      >
        Example Code
      </h2>
      {error ? (
        <div className="border border-slate-200 rounded-md overflow-hidden bg-red-50 p-4">
          <p className="text-sm text-red-600">{error}</p>
        </div>
      ) : (
        <div className="border border-slate-200 rounded-md overflow-hidden bg-slate-900 p-4">
          <pre className="text-sm text-white overflow-x-auto" dangerouslySetInnerHTML={{ __html: highlightedCode }} />
        </div>
      )}
      <p className="mt-2 text-sm text-slate-500">
        {commentStyle === 'detailed' ? 'Detailed DevOps commentary included' : 'Minimalist code style'}
      </p>
    </section>
  );
};